version: '3.2'

services:

  mediawiki:
      build:
        context: .
        args:
          MW_VERSION: ${MW_VERSION}
          MW_PATCH_VERSION: ${MW_PATCH_VERSION}
          COMPOSER_HASH: ${COMPOSER_HASH}

      volumes:
        - "mediawiki:/var/www/mediawiki"
#        - "./www/LocalSettings.php:/var/www/mediawiki/LocalSettings.php"
#        - "./www/images:/var/www/mediawiki/images"

  nginx:
      image: nginx:stable-alpine
      volumes:
        - "./etc/nginx.conf:/etc/nginx/nginx.conf"
        - "mediawiki:/var/www/mediawiki"
      depends_on: 
        - mediawiki
      ports:
        - "80:80"

  db:
      image: mariadb:latest
      restart: always
      environment:
        - "MYSQL_USER=mediawiki"
        - "MYSQL_PASSWORD=mediawiki"
        - "MYSQL_DATABASE=mediawiki"
        - "MYSQL_ROOT_PASSWORD=mediawiki"

volumes:
  mediawiki:
