version: '3.2'

services:

  mediawiki:
      build: .
      volumes:
        - "mediawiki:/var/www/mediawiki"
#        - "./www/LocalSettings.php:/var/www/mediawiki/LocalSettings.php"
#        - "./www/images:/var/www/mediawiki/images"

  nginx:
      image: nginx:1.15.2-alpine
      volumes:
        - "./etc/nginx.conf:/etc/nginx/nginx.conf"
        - "mediawiki:/var/www/mediawiki"
      depends_on: 
        - mediawiki
      ports:
        - "80:80"

  db:
      image: mysql/mysql-server:latest
      environment:
        - "MYSQL_USER=mediawiki"
        - "MYSQL_PASSWORD=mediawiki"
        - "MYSQL_DATABASE=mediawiki"
        - "MYSQL_ROOT_PASSWORD=mediawiki"

volumes:
  mediawiki:
