name: Docker Image CD

on:
  push:
    branches:
      - master

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            MW_VERSION=${{ env.MW_VERSION }}
            MW_PATCH_VERSION=${{ env.MW_PATCH_VERSION }}
            COMPOSER_HASH=${{ env.COMPOSER_HASH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/chiefy/alpine-mediawiki:latest
            ghcr.io/chiefy/alpine-mediawiki:${{ env.MW_VERSION }}${{ env.MW_PATCH_VERSION }}            